apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - prefill.yaml
  - decode.yaml
  - router.yaml
  - services.yaml
  - serviceAccount.yaml
  - launcher-configmap.yaml
  - rbac.yaml
